name: dmg_io_mobile
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animated_icon_button: ^0.3.0
  badges: ^1.1.4
  bubble_animated_tabbar: ^1.0.2
  cloud_firestore: null
  collection: null
  colorful_safe_area: null
  cupertino_icons: null
  expandable: null
  firebase_auth: null
  firebase_core: null
  firebase_dynamic_links: null
  firebase_storage: ^5.0.1
  flip_card: ^0.4.4
  flutter_echarts: null
  flutter_hooks: null
  flutter_icons: null
  flutter_inner_drawer: null
  flutter_native_timezone: null
  flutter_sequence_animation: null
  flutter_skeleton: null
  flutter_spinkit: null
  flutter_svg: ^0.19.1
  freezed_annotation: null
  google_sign_in: null
  graphview: null
  grouped_list: ^3.5.0
  hooks_riverpod: null
  jdenticon: ^1.0.1
  json_annotation: null
  lipsum: ^1.0.1
  modal_bottom_sheet: null
  nested: null
  recase: null
  row_collection: ^0.2.4
  rxdart: null
  sealed_unions: null
  shared_preferences: null
  shimmer: null
  stack_trace: null
  state_notifier: null
  sticky_headers: ^0.1.8+1
  string_validator: ^0.1.4
  supercharged: null
  union: null
  uuid: null

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: null
  freezed: null
  json_serializable: null

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/images/app_icons/
    - assets/images/onboarding/
    - assets/images/app/
